#ifndef GAUDIKERNEL_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define GAUDIKERNEL_MAJOR_VERSION 31
#define GAUDIKERNEL_MINOR_VERSION 4
#define GAUDIKERNEL_PATCH_VERSION 0
#define GAUDIKERNEL_VERSION CALC_GAUDI_VERSION(GAUDIKERNEL_MAJOR_VERSION,GAUDIKERNEL_MINOR_VERSION)
#endif
