#ifndef GAUDIPLUGINSERVICE_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define GAUDIPLUGINSERVICE_MAJOR_VERSION 1
#define GAUDIPLUGINSERVICE_MINOR_VERSION 2
#define GAUDIPLUGINSERVICE_PATCH_VERSION 0
#define GAUDIPLUGINSERVICE_VERSION CALC_GAUDI_VERSION(GAUDIPLUGINSERVICE_MAJOR_VERSION,GAUDIPLUGINSERVICE_MINOR_VERSION)
#endif
