#ifndef GAUDIMONITOR_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define GAUDIMONITOR_MAJOR_VERSION 5
#define GAUDIMONITOR_MINOR_VERSION 3
#define GAUDIMONITOR_PATCH_VERSION 0
#define GAUDIMONITOR_VERSION CALC_GAUDI_VERSION(GAUDIMONITOR_MAJOR_VERSION,GAUDIMONITOR_MINOR_VERSION)
#endif
