# CMake generated Testfile for 
# Source directory: /home/jwsmith/ANA/2_GAUDI/Gaudi/GaudiKernel
# Build directory: /home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/GaudiKernel
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(GaudiKernel.DirSearchPath_test "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi/cmake/env.py" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/config/GaudiBuildEnvironment.xml" "DirSearchPath_test.exe")
SET_TESTS_PROPERTIES(GaudiKernel.DirSearchPath_test PROPERTIES  WORKING_DIRECTORY ".")
ADD_TEST(GaudiKernel.test_SerializeSTL "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi/cmake/env.py" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/config/GaudiBuildEnvironment.xml" "test_SerializeSTL.exe")
SET_TESTS_PROPERTIES(GaudiKernel.test_SerializeSTL PROPERTIES  WORKING_DIRECTORY ".")
ADD_TEST(GaudiKernel.PathResolver_test "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi/cmake/env.py" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/config/GaudiBuildEnvironment.xml" "PathResolver_test.exe")
SET_TESTS_PROPERTIES(GaudiKernel.PathResolver_test PROPERTIES  WORKING_DIRECTORY "/home/jwsmith/ANA/2_GAUDI/Gaudi/GaudiKernel/tests")
ADD_TEST(GaudiKernel.test_GaudiTime "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi/cmake/env.py" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/config/GaudiBuildEnvironment.xml" "test_GaudiTime.exe")
SET_TESTS_PROPERTIES(GaudiKernel.test_GaudiTime PROPERTIES  WORKING_DIRECTORY ".")
ADD_TEST(GaudiKernel.test_GaudiTiming "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi/cmake/env.py" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/config/GaudiBuildEnvironment.xml" "test_GaudiTiming.exe")
SET_TESTS_PROPERTIES(GaudiKernel.test_GaudiTiming PROPERTIES  WORKING_DIRECTORY ".")
ADD_TEST(GaudiKernel.Parsers_test "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi/cmake/env.py" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/config/GaudiBuildEnvironment.xml" "Parsers_test.exe")
SET_TESTS_PROPERTIES(GaudiKernel.Parsers_test PROPERTIES  WORKING_DIRECTORY ".")
ADD_TEST(GaudiKernel.Memory_test "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi/cmake/env.py" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/config/GaudiBuildEnvironment.xml" "Memory_test.exe")
SET_TESTS_PROPERTIES(GaudiKernel.Memory_test PROPERTIES  WORKING_DIRECTORY ".")
ADD_TEST(GaudiKernel.test_headers_build "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi/cmake/env.py" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/config/GaudiBuildEnvironment.xml" "test_headers_build.exe")
SET_TESTS_PROPERTIES(GaudiKernel.test_headers_build PROPERTIES  WORKING_DIRECTORY ".")
ADD_TEST(GaudiKernel.confdb "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi/cmake/env.py" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/config/GaudiBuildEnvironment.xml" "nosetests" "/home/jwsmith/ANA/2_GAUDI/Gaudi/GaudiKernel/tests/nose/confdb")
SET_TESTS_PROPERTIES(GaudiKernel.confdb PROPERTIES  WORKING_DIRECTORY ".")
ADD_TEST(GaudiKernel.genconf_with_custom_factory "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi/cmake/env.py" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/config/GaudiBuildEnvironment.xml" "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi/cmake/env.py" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/config/GaudiBuildEnvironment.xml" "genconf.exe" "-o" "/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/GaudiKernel/custom_factory_testdir" "-p" "CustomFactoryTest" "-i" "test_CustomFactory")
SET_TESTS_PROPERTIES(GaudiKernel.genconf_with_custom_factory PROPERTIES  WORKING_DIRECTORY "/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/GaudiKernel/custom_factory_testdir")
ADD_TEST(GaudiKernel.QMTest "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi/cmake/env.py" "-s" "QMTESTLOCALDIR=/home/jwsmith/ANA/2_GAUDI/Gaudi/GaudiKernel/tests/qmtest" "-s" "QMTESTRESULTS=/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/GaudiKernel/tests/qmtest/results.qmr" "-s" "QMTESTRESULTSDIR=/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/GaudiKernel/tests/qmtest" "-s" "GAUDI_QMTEST_HTML_OUTPUT=/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/test_results" "-s" "GAUDI_QMTEST_XML_OUTPUT=/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/xml_test_results" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/config/GaudiBuildEnvironment.xml" "run_qmtest.py" "GaudiKernel")
SET_TESTS_PROPERTIES(GaudiKernel.QMTest PROPERTIES  WORKING_DIRECTORY ".")
