#ifndef GAUDIRELEASE_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define GAUDIRELEASE_MAJOR_VERSION 26
#define GAUDIRELEASE_MINOR_VERSION 1
#define GAUDIRELEASE_PATCH_VERSION 0
#define GAUDIRELEASE_VERSION CALC_GAUDI_VERSION(GAUDIRELEASE_MAJOR_VERSION,GAUDIRELEASE_MINOR_VERSION)
#endif
