#ifndef GAUDIAUD_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define GAUDIAUD_MAJOR_VERSION 10
#define GAUDIAUD_MINOR_VERSION 2
#define GAUDIAUD_PATCH_VERSION 0
#define GAUDIAUD_VERSION CALC_GAUDI_VERSION(GAUDIAUD_MAJOR_VERSION,GAUDIAUD_MINOR_VERSION)
#endif
