#ifndef GAUDISYS_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define GAUDISYS_MAJOR_VERSION 26
#define GAUDISYS_MINOR_VERSION 1
#define GAUDISYS_PATCH_VERSION 0
#define GAUDISYS_VERSION CALC_GAUDI_VERSION(GAUDISYS_MAJOR_VERSION,GAUDISYS_MINOR_VERSION)
#endif
