# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "RPM")
SET(CPACK_INSTALL_CMAKE_PROJECTS "/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/build.aarch64-ubuntu14.04-gcc49-opt;Gaudi;ALL;/")
SET(CPACK_INSTALL_PREFIX "/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/InstallArea/aarch64-ubuntu14.04-gcc49-opt")
SET(CPACK_MODULE_PATH "/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/cmake;/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/cmake/modules;/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1")
SET(CPACK_NSIS_DISPLAY_NAME "Gaudi 26.1.1")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "Gaudi 26.1.1")
SET(CPACK_OUTPUT_CONFIG_FILE "/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/build.aarch64-ubuntu14.04-gcc49-opt/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/usr")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Gaudi built using CMake")
SET(CPACK_PACKAGE_FILE_NAME "Gaudi-26.1.1-aarch64-ubuntu14.04-gcc49-opt")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "Gaudi 26.1.1")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Gaudi 26.1.1")
SET(CPACK_PACKAGE_NAME "Gaudi")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "Humanity")
SET(CPACK_PACKAGE_VERSION "26.1.1")
SET(CPACK_PACKAGE_VERSION_MAJOR "26")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "1")
SET(CPACK_RESOURCE_FILE_LICENSE "/usr/share/cmake-2.8/Templates/CPack.GenericLicense.txt")
SET(CPACK_RESOURCE_FILE_README "/usr/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-2.8/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "RPM")
SET(CPACK_SOURCE_IGNORE_FILES "/InstallArea/;/build\\..*/;/\\.svn/;/\\.git/;/\\.settings/;\\..*project;\\.gitignore")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/build.aarch64-ubuntu14.04-gcc49-opt/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_RPM "ON")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "")
SET(CPACK_SYSTEM_NAME "aarch64-ubuntu14.04-gcc49-opt")
SET(CPACK_TOPLEVEL_TAG "aarch64-ubuntu14.04-gcc49-opt")
SET(CPACK_WIX_SIZEOF_VOID_P "8")
