# CMake generated Testfile for 
# Source directory: /home/jwsmith/ANA/2_GAUDI/Gaudi-26r1
# Build directory: /home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/build.aarch64-ubuntu14.04-gcc49-opt
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(cmake.EnvConfigTests "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/cmake/xenv" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/build.aarch64-ubuntu14.04-gcc49-opt/config/Gaudi-build.xenv" "nosetests" "--with-doctest" "/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/cmake/EnvConfig")
SET_TESTS_PROPERTIES(cmake.EnvConfigTests PROPERTIES  LABELS "Gaudi-26r1" WORKING_DIRECTORY ".")
ADD_TEST(cmake.project_manifest.doctest "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/cmake/xenv" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/build.aarch64-ubuntu14.04-gcc49-opt/config/Gaudi-build.xenv" "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "-m" "doctest" "/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/GaudiPolicy/scripts/project_manifest.py")
SET_TESTS_PROPERTIES(cmake.project_manifest.doctest PROPERTIES  LABELS "Gaudi-26r1" WORKING_DIRECTORY ".")
ADD_TEST(cmake.CMakeModules "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/cmake/xenv" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/build.aarch64-ubuntu14.04-gcc49-opt/config/Gaudi-build.xenv" "nosetests" "/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/cmake/tests")
SET_TESTS_PROPERTIES(cmake.CMakeModules PROPERTIES  LABELS "Gaudi-26r1" WORKING_DIRECTORY ".")
ADD_TEST(cmake.QMTDeps "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/cmake/xenv" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/build.aarch64-ubuntu14.04-gcc49-opt/config/Gaudi-build.xenv" "nosetests" "--with-doctest" "/home/jwsmith/ANA/2_GAUDI/Gaudi-26r1/cmake/extract_qmtest_metadata.py")
SET_TESTS_PROPERTIES(cmake.QMTDeps PROPERTIES  LABELS "Gaudi-26r1" WORKING_DIRECTORY ".")
SUBDIRS(GaudiPluginService)
SUBDIRS(GaudiKernel)
SUBDIRS(Gaudi)
SUBDIRS(GaudiCoreSvc)
SUBDIRS(GaudiSvc)
SUBDIRS(GaudiUtils)
SUBDIRS(GaudiAlg)
SUBDIRS(GaudiPython)
SUBDIRS(GaudiGSL)
SUBDIRS(RootCnv)
SUBDIRS(GaudiExamples)
SUBDIRS(GaudiPolicy)
SUBDIRS(GaudiMonitor)
SUBDIRS(GaudiMP)
SUBDIRS(GaudiKernel/src/Util)
SUBDIRS(GaudiProfiling)
SUBDIRS(GaudiAud)
SUBDIRS(PartPropSvc)
SUBDIRS(RootHistCnv)
SUBDIRS(GaudiCommonSvc)
SUBDIRS(GaudiSys)
SUBDIRS(GaudiRelease)
SUBDIRS(GaudiRelease/doc/doxygen)
SUBDIRS(GaudiPartProp)
