#!/bin/sh
#!/bin/sh
export AtlasVersion=AtlasCore
function SuccessOrNot {
        if [ $1 -eq 0 ]; then
          echo "$(tput setaf 2) $2 succeeded" >> PASSorFAIL
        else
          echo "$(tput setaf 1) $2 FAILED" >> PASSorFAIL
        fi
}

alias athena.py='timeout 100 athena.py'

function runTest {
        echo "$(tput setaf 1)$(tput setab 7) Starting new test: $1 $(tput sgr 0)"
        athena.py $1
        SuccessOrNot $? $1
}
runTest AthenaDBTestRec/ReadRefDBExample.py
runTest AthenaServices/MultiplePass_test.py
runTest EventLoopTest/ByteStreamReadTest.py
runTest AthenaServices/MixingEventSelector_test.py

