#ifndef PARTPROPSVC_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define PARTPROPSVC_MAJOR_VERSION 5
#define PARTPROPSVC_MINOR_VERSION 1
#define PARTPROPSVC_PATCH_VERSION 0
#define PARTPROPSVC_VERSION CALC_GAUDI_VERSION(PARTPROPSVC_MAJOR_VERSION,PARTPROPSVC_MINOR_VERSION)
#endif
