-- Experiment prefix
--define EXPERIMENT=ATLAS;
define EXPERIMENT=TESTEXP;

-- Temp tablespace
define TEMP_TS=TEMP;
--define TEMP_TS=TEMP01;

-- Generic reader user
define USER_R_SUFFIX=_COOL_READER
define USER_R=&EXPERIMENT&USER_R_SUFFIX;

/* For tests */
define DETECTOR=TESTDET;

/* Accounts created on 2005/07/26 */
--define DETECTOR=INDET;
--define DETECTOR=TRT;
--define DETECTOR=LAR;
--define DETECTOR=TILE;
--define DETECTOR=MUON;
--define DETECTOR=MUONALIGN;
--define DETECTOR=MDT;
--define DETECTOR=TDAQ;
--define DETECTOR=DCS;
--define DETECTOR=GLOBAL;

/* Accounts created on 2005/09/29 */
--define DETECTOR=SCT;
--define DETECTOR=PIXEL;

-- Owner user
define USER_SUFFIX=_COOL_
define USER_O=&EXPERIMENT&USER_SUFFIX&DETECTOR;

-- Data tablespace
define DATA_TS_SUFFIX=_DATA01;
define DATA_TS=&USER_O&DATA_TS_SUFFIX;

-- Password
define PSWD_SUFFIX=_password
define PSWD_O=&USER_O&PSWD_SUFFIX

-- Roles
define R_ROLE_SUFFIX=_R;
define R_ROLE=R_&USER_O&R_ROLE_SUFFIX;
define W_ROLE_SUFFIX=_W;
define W_ROLE=R_&USER_O&W_ROLE_SUFFIX;
define T_ROLE_SUFFIX=_T;
define T_ROLE=R_&USER_O&T_ROLE_SUFFIX;

-- Writer user
define USER_W=&USER_O&W_ROLE_SUFFIX;
define PSWD_W=&USER_W&PSWD_SUFFIX

-- CROSS CHECK!
--select '&DETECTOR', '&USER_R', '&USER_O', '&DATA_TS', '&R_ROLE', '&W_ROLE', '&T_ROLE', '&USER_W', '&PSWD_O', '&PSWD_W' from DUAL;

/*
--DROP TABLESPACE &DATA_TS INCLUDING CONTENTS AND DATAFILES;
--DROP USER &USER_O CASCADE;
--DROP ROLE &R_ROLE;
--DROP ROLE &W_ROLE;
--DROP ROLE &T_ROLE;
--DROP USER &USER_W CASCADE;
--*/

--/*
-- Create tablespace
CREATE TABLESPACE &DATA_TS
DATAFILE SIZE 128M AUTOEXTEND ON NEXT 128M MAXSIZE 8192M LOGGING
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

-- Create owner
CREATE USER &USER_O
PROFILE CERN_DEV_PROFILE
IDENTIFIED BY &PSWD_O
DEFAULT TABLESPACE &DATA_TS
TEMPORARY TABLESPACE &TEMP_TS
QUOTA UNLIMITED ON &DATA_TS;

GRANT CERN_DEV_ROLE TO &USER_O;

-- Create roles
CREATE ROLE &R_ROLE;
CREATE ROLE &W_ROLE;
CREATE ROLE &T_ROLE;

-- Create writer
CREATE USER &USER_W
PROFILE CERN_APP_PROFILE
IDENTIFIED BY &PSWD_W
DEFAULT TABLESPACE &DATA_TS
TEMPORARY TABLESPACE &TEMP_TS
QUOTA 10M ON &DATA_TS;

GRANT CERN_APP_ROLE TO &USER_W;

GRANT &R_ROLE TO &USER_W;
GRANT &W_ROLE TO &USER_W;
GRANT &T_ROLE TO &USER_W;

-- Grant reader role to generic reader
GRANT &R_ROLE TO &USER_R;
--*/
