#ifndef ROOTHISTCNV_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define ROOTHISTCNV_MAJOR_VERSION 12
#define ROOTHISTCNV_MINOR_VERSION 1
#define ROOTHISTCNV_PATCH_VERSION 0
#define ROOTHISTCNV_VERSION CALC_GAUDI_VERSION(ROOTHISTCNV_MAJOR_VERSION,ROOTHISTCNV_MINOR_VERSION)
#endif
