#ifndef GAUDIPOLICY_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define GAUDIPOLICY_MAJOR_VERSION 15
#define GAUDIPOLICY_MINOR_VERSION 4
#define GAUDIPOLICY_PATCH_VERSION 0
#define GAUDIPOLICY_VERSION CALC_GAUDI_VERSION(GAUDIPOLICY_MAJOR_VERSION,GAUDIPOLICY_MINOR_VERSION)
#endif
