# CMake generated Testfile for 
# Source directory: /home/jwsmith/ANA/2_GAUDI/Gaudi/GaudiExamples
# Build directory: /home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/GaudiExamples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(GaudiExamples.Properties "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi/cmake/env.py" "-s" "JOBOPTSEARCHPATH=/home/jwsmith/ANA/2_GAUDI/Gaudi/GaudiExamples/options" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/config/GaudiBuildEnvironment.xml" "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi/Gaudi/scripts/gaudirun.py" "/home/jwsmith/ANA/2_GAUDI/Gaudi/GaudiExamples/options/Properties.opts")
SET_TESTS_PROPERTIES(GaudiExamples.Properties PROPERTIES  WORKING_DIRECTORY ".")
ADD_TEST(GaudiExamples.AlgTools "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi/cmake/env.py" "-s" "JOBOPTSEARCHPATH=/home/jwsmith/ANA/2_GAUDI/Gaudi/GaudiExamples/options" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/config/GaudiBuildEnvironment.xml" "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi/Gaudi/scripts/gaudirun.py" "/home/jwsmith/ANA/2_GAUDI/Gaudi/GaudiExamples/options/AlgTools.opts")
SET_TESTS_PROPERTIES(GaudiExamples.AlgTools PROPERTIES  WORKING_DIRECTORY ".")
ADD_TEST(GaudiExamples.QMTest "/home/seuster/LCGStack/lcgcmake-install/Python/2.7.9/aarch64-ubuntu14.04-gcc49-opt/bin/python" "/home/jwsmith/ANA/2_GAUDI/Gaudi/cmake/env.py" "-s" "STDOPTS=/home/jwsmith/ANA/2_GAUDI/Gaudi/GaudiExamples/options" "-s" "JOBOPTSEARCHPATH=/home/jwsmith/ANA/2_GAUDI/Gaudi/GaudiExamples/options" "-p" "PYTHONPATH=/home/jwsmith/ANA/2_GAUDI/Gaudi/GaudiExamples/tests/qmtest" "-s" "QMTESTLOCALDIR=/home/jwsmith/ANA/2_GAUDI/Gaudi/GaudiExamples/tests/qmtest" "-s" "QMTESTRESULTS=/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/GaudiExamples/tests/qmtest/results.qmr" "-s" "QMTESTRESULTSDIR=/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/GaudiExamples/tests/qmtest" "-s" "GAUDI_QMTEST_HTML_OUTPUT=/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/test_results" "-s" "GAUDI_QMTEST_XML_OUTPUT=/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/xml_test_results" "--xml" "/home/jwsmith/ANA/2_GAUDI/Gaudi/build.aarch64-ubuntu14.04-gcc49-opt/config/GaudiBuildEnvironment.xml" "run_qmtest.py" "GaudiExamples")
SET_TESTS_PROPERTIES(GaudiExamples.QMTest PROPERTIES  WORKING_DIRECTORY ".")
