#ifndef GAUDIEXAMPLES_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define GAUDIEXAMPLES_MAJOR_VERSION 25
#define GAUDIEXAMPLES_MINOR_VERSION 3
#define GAUDIEXAMPLES_PATCH_VERSION 0
#define GAUDIEXAMPLES_VERSION CALC_GAUDI_VERSION(GAUDIEXAMPLES_MAJOR_VERSION,GAUDIEXAMPLES_MINOR_VERSION)
#endif
