set_property(TEST GaudiExamples.thistread APPEND PROPERTY DEPENDS GaudiExamples.thistwrite)
set_property(TEST GaudiExamples.evtcolread APPEND PROPERTY DEPENDS GaudiExamples.evtcolwrite)
set_property(TEST GaudiExamples.aida2rootex APPEND PROPERTY DEPENDS GaudiExamples.histoex2)
set_property(TEST GaudiExamples.evtcolwrite APPEND PROPERTY DEPENDS GaudiExamples.evtcolsex.prepare)
set_property(TEST GaudiExamples.histoex2 APPEND PROPERTY DEPENDS GaudiExamples.histoex1)
set_property(TEST GaudiExamples.return_codes.corrupted_input APPEND PROPERTY DEPENDS GaudiExamples.root_io.write)
set_property(TEST GaudiExamples.evtcolsex.write APPEND PROPERTY DEPENDS GaudiExamples.evtcolsex.prepare)
set_property(TEST GaudiExamples.evtcolsex.read APPEND PROPERTY DEPENDS GaudiExamples.evtcolsex.write)
set_property(TEST GaudiExamples.multi_input.read APPEND PROPERTY DEPENDS GaudiExamples.multi_input.prepare_base GaudiExamples.multi_input.prepare_ext)
set_property(TEST GaudiExamples.root_io.read APPEND PROPERTY DEPENDS GaudiExamples.root_io.write)
set_property(TEST GaudiExamples.root_io.coll.write APPEND PROPERTY DEPENDS GaudiExamples.root_io.write)
set_property(TEST GaudiExamples.root_io.coll.read APPEND PROPERTY DEPENDS GaudiExamples.root_io.coll.write GaudiExamples.root_io.read)
set_property(TEST GaudiExamples.root_io.extcoll.write APPEND PROPERTY DEPENDS GaudiExamples.root_io.write GaudiExamples.root_io.coll.write)
set_property(TEST GaudiExamples.root_io.extcoll.read APPEND PROPERTY DEPENDS GaudiExamples.root_io.extcoll.write GaudiExamples.root_io.coll.read)
set_property(TEST GaudiExamples.jira.gaudi_971 APPEND PROPERTY DEPENDS GaudiExamples.root_io.write)
set_property(TEST GaudiExamples.conditional_output.read APPEND PROPERTY DEPENDS GaudiExamples.conditional_output.write)
set_property(TEST GaudiExamples.bug_101513.with_error APPEND PROPERTY DEPENDS GaudiExamples.bug_101513.prepare)
set_property(TEST GaudiExamples.bug_101513.without_error APPEND PROPERTY DEPENDS GaudiExamples.bug_101513.prepare)
set_property(TEST GaudiExamples.gaudimt APPEND PROPERTY LABELS disabled)
