#ifndef GAUDIGSL_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define GAUDIGSL_MAJOR_VERSION 8
#define GAUDIGSL_MINOR_VERSION 2
#define GAUDIGSL_PATCH_VERSION 0
#define GAUDIGSL_VERSION CALC_GAUDI_VERSION(GAUDIGSL_MAJOR_VERSION,GAUDIGSL_MINOR_VERSION)
#endif
