#ifndef GAUDIPROFILING_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define GAUDIPROFILING_MAJOR_VERSION 2
#define GAUDIPROFILING_MINOR_VERSION 1
#define GAUDIPROFILING_PATCH_VERSION 0
#define GAUDIPROFILING_VERSION CALC_GAUDI_VERSION(GAUDIPROFILING_MAJOR_VERSION,GAUDIPROFILING_MINOR_VERSION)
#endif
