#ifndef GAUDIPYTHON_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define GAUDIPYTHON_MAJOR_VERSION 13
#define GAUDIPYTHON_MINOR_VERSION 4
#define GAUDIPYTHON_PATCH_VERSION 0
#define GAUDIPYTHON_VERSION CALC_GAUDI_VERSION(GAUDIPYTHON_MAJOR_VERSION,GAUDIPYTHON_MINOR_VERSION)
#endif
