lcgcmt_installarea=without_installarea
CMTPATH=/home/jwsmith/HDD/CORAL/CORAL-2-4-2:/home/jwsmith/HDD:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
CMT_tag=$(tag)
CMTROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/cmt/v1r26p20140131/armv7l-fc21-gcc49-opt/CMT/v1r26p20140131
CMT_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/cmt/v1r26p20140131/armv7l-fc21-gcc49-opt/CMT/v1r26p20140131
CMTVERSION=v1r26p20140131
CMT_cmtpath=/home/jwsmith/HDD
CMT_offset=lcgcmake-install-gcc49/cmt/v1r26p20140131/armv7l-fc21-gcc49-opt
CMT_project=jwsmith
CMT_project_release=HDD
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/../armv7l-fc21-gcc49-opt/examples/bin:/home/jwsmith/HDD/CORAL/CORAL-2-4-2/../armv7l-fc21-gcc49-opt/tests/bin:/home/jwsmith/HDD/CORAL/CORAL-2-4-2/../${CMTCONFIG}/bin:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../tcmalloc/1.7p3/armv7l-fc21-gcc49-opt/bin:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../igprof/5.9.11/armv7l-fc21-gcc49-opt/bin:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../valgrind/3.10.0/armv7l-fc21-gcc49-opt/bin:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../QMtest/2.4.1_python2.7/armv7l-fc21-gcc49-opt/bin:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../frontier_client/2.8.10/armv7l-fc21-gcc49-opt/bin:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../sqlite/3070900/armv7l-fc21-gcc49-opt/bin:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../mysql/5.5.27/armv7l-fc21-gcc49-opt/bin:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../oracle/11.2.0.3.0/armv7l-fc21-gcc49-opt/bin:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../XercesC/3.1.1p1/armv7l-fc21-gcc49-opt/bin:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../Python/2.7.6/armv7l-fc21-gcc49-opt/bin:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../gcc/4.9.1/UnknownArch-fc21/bin:/home/jwsmith/HDD/../armv7l-fc21-gcc49-opt/examples/bin:/home/jwsmith/HDD/../armv7l-fc21-gcc49-opt/tests/bin:/home/jwsmith/HDD/lcgcmake-install-gcc49/ROOT/5.34.24/armv7l-fc21-gcc49-opt/bin:/home/jwsmith/HDD/COOL/COOL_2_9_2/../armv7l-fc21-gcc49-opt/examples/bin:/home/jwsmith/HDD/COOL/COOL_2_9_2/../armv7l-fc21-gcc49-opt/tests/bin:/home/jwsmith/HDD/COOL/COOL_2_9_2/bin:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../qt/4.8.4/armv7l-fc21-gcc49-opt/bin:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../xrootd/3.3.6/armv7l-fc21-gcc49-opt/bin:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../gccxml/0.9.0_20131026/armv7l-fc21-gcc49-opt/bin:/usr/lib/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/jwsmith/.local/bin:/home/jwsmith/bin:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../CORAL/CORAL_2_4_4/armv7l-fc21-gcc49-opt/bin:/home/jwsmith/HDD/lcgcmake-install-gcc49/cmt/v1r26p20140131/armv7l-fc21-gcc49-opt/CMT/v1r26p20140131/${CMTBIN}
CLASSPATH=/home/jwsmith/HDD/lcgcmake-install-gcc49/cmt/v1r26p20140131/armv7l-fc21-gcc49-opt/CMT/v1r26p20140131/java
debug_option=-g
cc=$(cc_name)
cflags=$(cppflags) -std=c11 
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
vsCONFIG=Release
vsOptimize=2
ppcmd=-I
preproc=c++ -MD -c 
cpp=$(cpp_name)
cppdebugflags=$(cppoptimized_s)
cppflags= $(cppmacros) -fPIC -pipe -ansi -Wall -W -pthread  -std=c++11 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplinkflags= -ldl -fpic -pthread -Wl,-E 
cpplink=$(cpplinkname) $(cpplinkflags)
for=$(for_name)
fflags=-O -fno-automatic -fdollar-ok -ff90 -w
fcomp=$(for) -c $(fincludes) $(fdebugflags) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=$(cpp_name) $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=${symlink}
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
library_prefix=lib
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=python ${CMTROOT}/mgr/cmt_svn_checkout.py 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
GUID_all={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC955}
package_GUID={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}
install_command=cp 
uninstall_command=/bin/rm -f 
cmt_installarea_command=cp 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=..
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=armv7l-fedora21-gcc492
config_tag=$(tag)
CONFIGROOT=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/config
config_root=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/config
CONFIGVERSION=v1
config_cmtpath=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
config_project=CORAL
config_project_release=CORAL-2-4-2
CoralBase_tag=$(tag)
CORALBASEROOT=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/CoralBase
CoralBase_root=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/CoralBase
CORALBASEVERSION=CoralBase-1-9-0
CoralBase_cmtpath=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
CoralBase_project=CORAL
CoralBase_project_release=CORAL-2-4-2
LCG_Policy_tag=$(tag)
LCG_POLICYROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Policy
LCG_Policy_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Policy
LCG_POLICYVERSION=v1
LCG_Policy_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
LCG_Policy_project=LCGCMT
LCG_Policy_project_release=LCGCMT_71
LCG_Settings_tag=$(tag)
LCG_SETTINGSROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings
LCG_Settings_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings
LCG_SETTINGSVERSION=v1
LCG_Settings_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
LCG_Settings_project=LCGCMT
LCG_Settings_project_release=LCGCMT_71
LCG_releases=$(LCG_Settings_root)/../../..
LCG_external=$(LCG_Settings_root)/../../..
unixdirname=lib
gcc_config_version=4.9.1
gcc_native_version=$(gcc_config_version)
gcc_home=$(LCG_external)/gcc/$(gcc_native_version)/$(LCG_hostos)
clang_native_version=$(clang_config_version)
clang_home=$(LCG_external)/llvm/$(clang_native_version)/$(LCG_hostos)
icc_native_version=$(icc_config_version)
cc_name=gcc
cpp_name=g++
cpplinkname=$(cpp_name)
for_name=gfortran
COMPILER_PATH=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../gcc/4.9.1/UnknownArch-fc21/lib/gcc/UnknownArch-unknown-linux-gnu/4.9.1
LD_LIBRARY_PATH=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/../armv7l-fc21-gcc49-opt/tests/lib:/home/jwsmith/HDD/CORAL/CORAL-2-4-2/../armv7l-fc21-gcc49-opt/examples/lib:/home/jwsmith/HDD/CORAL/CORAL-2-4-2/../${CMTCONFIG}/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../tcmalloc/1.7p3/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../igprof/5.9.11/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../libunwind/5c2cade/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../CppUnit/1.12.1_p1/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../frontier_client/2.8.10/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../expat/2.0.1/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../sqlite/3070900/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../mysql/5.5.27/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../oracle/11.2.0.3.0/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../XercesC/3.1.1p1/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../uuid/1.42/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../Boost/1.55.0_python2.7/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../gcc/4.9.1/UnknownArch-fc21/lib:/home/jwsmith/HDD/../armv7l-fc21-gcc49-opt/tests/lib:/home/jwsmith/HDD/../armv7l-fc21-gcc49-opt/examples/lib:/home/jwsmith/HDD/CORAL/CORAL-2-4-2/InstallArea/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/ROOT/5.34.24/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/COOL/COOL_2_9_2/../armv7l-fc21-gcc49-opt/tests/lib:/home/jwsmith/HDD/COOL/COOL_2_9_2/../armv7l-fc21-gcc49-opt/examples/lib:/home/jwsmith/HDD/COOL/COOL_2_9_2/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../qt/4.8.4/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../xrootd/3.3.6/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../CORAL/CORAL_2_4_4/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../Python/2.7.6/armv7l-fc21-gcc49-opt/lib
merge_rootmap_cmd=$(LCG_Policy_root)/cmt/fragments/merge_files.py
vsDebug=2
cppdebugflags_s=-g
cppoptimized_s=-O2
cppprofiled_s=-pg
cdebugflags_s=-g
fdebugflags= $(foptimized_s)
fdebugflags_s=-g
foptimized_s=-O2
fprofiled_s=-pg
cppmacros= -Df2cFortran -fPIC -D_GNU_SOURCE -Dlinux -Dunix 
gcov_cppflags=-fprofile-arcs -ftest-coverage
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts= -shared -fPIC -Wl,-s -ldl -pthread 
libraryshr_linkopts= -shared -fPIC -ldl -pthread 
application_linkopts=-Wl,--export-dynamic 
libdirname=lib
bindirname=bin
Boost_tag=$(tag)
BOOSTROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/Boost
Boost_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/Boost
BOOSTVERSION=v1
Boost_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
Boost_offset=LCG_Interfaces
Boost_project=LCGCMT
Boost_project_release=LCGCMT_71
LCG_Configuration_tag=$(tag)
LCG_CONFIGURATIONROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Configuration
LCG_Configuration_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Configuration
LCG_CONFIGURATIONVERSION=v1
LCG_Configuration_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
LCG_Configuration_project=LCGCMT
LCG_Configuration_project_release=LCGCMT_71
LCG_Platforms_tag=$(tag)
LCG_PLATFORMSROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Platforms
LCG_Platforms_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Platforms
LCG_PLATFORMSVERSION=v1
LCG_Platforms_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
LCG_Platforms_project=LCGCMT
LCG_Platforms_project_release=LCGCMT_71
LCG_arch=armv7l
LCG_os=fc21
LCG_compiler=gcc49
LCG_mode=opt
LCG_basesystem=$(LCG_arch)-$(LCG_os)-$(LCG_compiler)
LCG_system=$(LCG_basesystem)-$(LCG_mode)
LCG_platform=$(LCG_basesystem)-$(LCG_mode)
ATLAS_TAGS_MAP=none
host_arch=UnknownArch
host_os=linux
host_cmtconfig=UnknownArch-linux-${host_compiler}-opt
LCG_hostos=$(host_arch)-$(LCG_os)
LCG_hostarch=$(host_arch)
LCG_config_version=71
uuid_config_version=1.42
4suite_config_version=1.0.2p1
AIDA_config_version=3.2.1
Boost_config_version=1.55.0
Boost_file_version=1_55
CASTOR_config_version=2.1.13-6
CLHEP_config_version=1.9.4.7
COOL_config_version=COOL_2_9_4
CORAL_config_version=CORAL_2_4_4
CppUnit_config_version=1.12.1_p1
Davix_config_version=0.3.1
Expat_config_version=2.0.1
FTS_config_version=2.2.8emi2
Frontier_Client_config_version=2.8.10
GCCXML_config_version=0.9.0_20131026
GSL_config_version=1.10
HepMC_config_version=2.06.09
HepPDT_config_version=2.06.01
LCGCMT_config_version=LCGCMT_71
Python_config_version=2.7.6
Python_config_version_twodigit=2.7
QMtest_config_version=2.4.1
Qt_config_version=4.8.4
RELAX_config_version=RELAX_1_3_0p
ROOT_config_version=5.34.24
WMS_config_version=3.4.0
XercesC_config_version=3.1.1p1
blas_config_version=20110419
cmaketools_config_version=1.1
cmt_config_version=v1r26p20140131
coin3d_config_version=3.1.3p2
coverage_config_version=3.5.2
cream_config_version=1.14.0-4
cx_oracle_config_version=5.1.1
dcap_config_version=2.47.7-1
dm-util_config_version=1.15.0-0
doxygen_config_version=1.8.2
dpm_config_version=1.8.5-1
epel_config_version=20130408
fastjet_config_version=3.1.0
fftw_config_version=3.1.2
genshi_config_version=0.6
gfal2_config_version=2.2.0-1
gfal_config_version=1.13.0-0
graphviz_config_version=2.28.0
gridftp_ifce_config_version=2.3.1-0
gridsite_config_version=1.7.25-1.emi2
igprof_config_version=5.9.11
ipython_config_version=0.12.1
is_ifce_config_version=1.15.0-0
json_config_version=2.5.2
lapack_config_version=3.5.0
lb_config_version=3.2.9
lcgdmcommon_config_version=1.8.5-1
lcginfosites_config_version=3.1.0-3
lcov_config_version=1.9
lfc_config_version=1.8.5-1
libsvm_config_version=2.86
libtool_config_version=1.5.26
libunwind_config_version=5c2cade
lxml_config_version=2.3
matplotlib_config_version=1.3.1
minuit_config_version=5.27.02
mock_config_version=0.8.0
mpich2_config_version=1.5
multiprocessing_config_version=2.6.2.1
mysql_config_version=5.5.27
mysql_python_config_version=1.2.3
neurobayes_config_version=3.7.0
neurobayes_expert_config_version=3.7.0
nose_config_version=1.1.2
numpy_config_version=1.8.0
oracle_config_version=11.2.0.3.0
pacparser_config_version=1.3.1
pcre_config_version=8.34
processing_config_version=0.52
py2neo_config_version=1.4.6
py_config_version=1.4.8
pyanalysis_config_version=1.4
pydot_config_version=1.0.28
pygraphics_config_version=1.4
pygsi_config_version=0.5
pylint_config_version=1.2.1
pyminuit_config_version=0.0.1
pyparsing_config_version=1.5.6
pyqt_config_version=4.9.5
pytest_config_version=2.2.4
pytools_config_version=1.8
pyxml_config_version=0.8.4p1
qwt_config_version=6.0.1
scipy_config_version=0.10.0
setuptools_config_version=0.6c11
sip_config_version=4.14
soqt_config_version=1.5.0
sqlalchemy_config_version=0.7.7
sqlite_config_version=3070900
srm_ifce_config_version=1.13.0-0
stomppy_config_version=3.1.3
storm_config_version=0.19
swig_config_version=2.0.11
sympy_config_version=0.7.1
tbb_config_version=42_20140122
tcmalloc_config_version=1.7p3
valgrind_config_version=3.10.0
vdt_config_version=0.3.6
voms_config_version=2.0.9-1
xqilla_config_version=2.2.4p1
xrootd_config_version=3.3.6
xrootd_python_config_version=0.1.3
Python_tag=$(tag)
PYTHONROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/Python
Python_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/Python
PYTHONVERSION=v1
Python_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
Python_offset=LCG_Interfaces
Python_project=LCGCMT
Python_project_release=LCGCMT_71
Python_native_version=$(Python_config_version)
Python_home=${LCG_external}/Python/$(Python_native_version)/$(LCG_system)
Python_inc=$(Python_home)/include/python$(Python_version)
Python_version=$(Python_config_version_twodigit)
Python_libversion_cmd=python -c "print ''.join('$(Python_config_version)'.split('.')[:2])"
Python_libversion=$(Python_config_version_twodigit)
DYLD_LIBRARY_PATH=/home/jwsmith/HDD/lcgcmake-install-gcc49/ROOT/5.34.24/armv7l-fc21-gcc49-opt/lib
Python_linkopts= -L$(Python_home)/lib -lpython$(Python_libversion) -lutil -lpthread 
Python_export_paths=$(Python_home)
MANPATH=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../tcmalloc/1.7p3/armv7l-fc21-gcc49-opt/share/man:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../igprof/5.9.11/armv7l-fc21-gcc49-opt/man:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../libunwind/5c2cade/armv7l-fc21-gcc49-opt/man:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../CppUnit/1.12.1_p1/armv7l-fc21-gcc49-opt/share/man:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../expat/2.0.1/armv7l-fc21-gcc49-opt/man:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../mysql/5.5.27/armv7l-fc21-gcc49-opt/man:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../uuid/1.42/armv7l-fc21-gcc49-opt/man:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../Python/2.7.6/armv7l-fc21-gcc49-opt/share/man:/home/jwsmith/HDD/lcgcmake-install-gcc49/ROOT/5.34.24/armv7l-fc21-gcc49-opt/man:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../gccxml/0.9.0_20131026/armv7l-fc21-gcc49-opt/share/man:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../ROOT/5.34.24/src/root/man
Boost_native_version=$(Boost_config_version)_python$(Python_config_version_twodigit)
Boost_home=$(LCG_external)/Boost/$(Boost_native_version)/$(LCG_system)
Boost_compiler_version=$(LCG_compiler)
Boost_linkopts=-L$(Boost_home)/lib 
Boost_linkopts_python= -lboost_python-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_system= -lboost_system-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_filesystem= -lboost_filesystem-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_filesystem_mt= -lboost_filesystem-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_iostreams= -lboost_iostreams-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_regex= -lboost_regex-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_thread= -lboost_thread-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_program_options= -lboost_program_options-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_serialization= -lboost_serialization-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_date_time= -lboost_date_time-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_graph= -lboost_graph-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_header_file_filter=$(Boost_home)/include/boost-$(Boost_file_version)
Boost_header_file_stamp=$(Boost_home)/include/boost-$(Boost_file_version)/boost/any.hpp
Boost_export_paths=$(Boost_home)
CoralBase_linkopts= -llcg_CoralBase  $(Boost_linkopts) $(Boost_linkopts_filesystem) $(Boost_linkopts_date_time) $(Boost_linkopts_system) $(Boost_linkopts_thread)
cmt_actions_constituents= make     
use_cppflags=  $(config_cppflags)  $(CoralCommon_cppflags)  $(RelationalAccess_cppflags)  $(CoralKernel_cppflags)  $(CoralBase_cppflags)  $(LCG_Policy_cppflags)  $(Boost_cppflags)  $(QMtest_cppflags)  $(Python_cppflags)  $(uuid_cppflags)  $(XercesC_cppflags)  $(oracle_cppflags)  $(mysql_cppflags)  $(sqlite_cppflags)  $(Frontier_Client_cppflags)  $(CppUnit_cppflags)  $(valgrind_cppflags)  $(igprof_cppflags)  $(tcmalloc_cppflags)  $(libunwind_cppflags)  $(LCG_Settings_cppflags)  $(LCG_Configuration_cppflags)  $(LCG_Platforms_cppflags)  $(PyCoral_cppflags)  $(ConnectionService_cppflags)  $(RelationalService_cppflags)  $(MonitoringService_cppflags)  $(XMLAuthenticationService_cppflags)  $(EnvironmentAuthenticationService_cppflags)  $(XMLLookupService_cppflags)  $(OracleAccess_cppflags)  $(MySQLAccess_cppflags)  $(SQLiteAccess_cppflags)  $(FrontierAccess_cppflags)  $(Tests_cppflags) 
lcg_CoralBase_shlibflags= $(Boost_linkopts) $(Boost_linkopts_filesystem) $(Boost_linkopts_date_time) $(Boost_linkopts_system) $(Boost_linkopts_thread)
RelationalAccess_tag=$(tag)
RELATIONALACCESSROOT=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/RelationalAccess
RelationalAccess_root=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/RelationalAccess
RELATIONALACCESSVERSION=RelationalAccess-1-8-1
RelationalAccess_cmtpath=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
RelationalAccess_project=CORAL
RelationalAccess_project_release=CORAL-2-4-2
RelationalAccess_linkopts= -llcg_RelationalAccess 
CoralKernel_tag=$(tag)
CORALKERNELROOT=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/CoralKernel
CoralKernel_root=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/CoralKernel
CORALKERNELVERSION=CoralKernel-0-0-5
CoralKernel_cmtpath=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
CoralKernel_project=CORAL
CoralKernel_project_release=CORAL-2-4-2
CoralKernel_linkopts= -llcg_CoralKernel 
CoralCommon_tag=$(tag)
CORALCOMMONROOT=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/CoralCommon
CoralCommon_root=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/CoralCommon
CORALCOMMONVERSION=CoralCommon-1-6-X-back
CoralCommon_cmtpath=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
CoralCommon_project=CORAL
CoralCommon_project_release=CORAL-2-4-2
CoralCommon_linkopts= -llcg_CoralCommon 
PyCoral_tag=$(tag)
PYCORALROOT=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/PyCoral
PyCoral_root=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/PyCoral
PYCORALVERSION=PyCoral-1-1-1
PyCoral_cmtpath=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
PyCoral_project=CORAL
PyCoral_project_release=CORAL-2-4-2
ConnectionService_tag=$(tag)
CONNECTIONSERVICEROOT=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/ConnectionService
ConnectionService_root=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/ConnectionService
CONNECTIONSERVICEVERSION=ConnectionService-2-9-1
ConnectionService_cmtpath=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
ConnectionService_project=CORAL
ConnectionService_project_release=CORAL-2-4-2
RelationalService_tag=$(tag)
RELATIONALSERVICEROOT=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/RelationalService
RelationalService_root=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/RelationalService
RELATIONALSERVICEVERSION=RelationalService-1-1-0
RelationalService_cmtpath=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
RelationalService_project=CORAL
RelationalService_project_release=CORAL-2-4-2
MonitoringService_tag=$(tag)
MONITORINGSERVICEROOT=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/MonitoringService
MonitoringService_root=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/MonitoringService
MONITORINGSERVICEVERSION=MonitoringService-1-1-0
MonitoringService_cmtpath=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
MonitoringService_project=CORAL
MonitoringService_project_release=CORAL-2-4-2
XMLAuthenticationService_tag=$(tag)
XMLAUTHENTICATIONSERVICEROOT=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/XMLAuthenticationService
XMLAuthenticationService_root=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/XMLAuthenticationService
XMLAUTHENTICATIONSERVICEVERSION=XMLAuthenticationService-1-2-X-back
XMLAuthenticationService_cmtpath=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
XMLAuthenticationService_project=CORAL
XMLAuthenticationService_project_release=CORAL-2-4-2
EnvironmentAuthenticationService_tag=$(tag)
ENVIRONMENTAUTHENTICATIONSERVICEROOT=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/EnvironmentAuthenticationService
EnvironmentAuthenticationService_root=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/EnvironmentAuthenticationService
ENVIRONMENTAUTHENTICATIONSERVICEVERSION=EnvironmentAuthenticationService-1-2-0
EnvironmentAuthenticationService_cmtpath=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
EnvironmentAuthenticationService_project=CORAL
EnvironmentAuthenticationService_project_release=CORAL-2-4-2
XMLLookupService_tag=$(tag)
XMLLOOKUPSERVICEROOT=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/XMLLookupService
XMLLookupService_root=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/XMLLookupService
XMLLOOKUPSERVICEVERSION=XMLLookupService-1-1-X-back
XMLLookupService_cmtpath=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
XMLLookupService_project=CORAL
XMLLookupService_project_release=CORAL-2-4-2
OracleAccess_tag=$(tag)
ORACLEACCESSROOT=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/OracleAccess
OracleAccess_root=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/OracleAccess
ORACLEACCESSVERSION=OracleAccess-1-7-3
OracleAccess_cmtpath=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
OracleAccess_project=CORAL
OracleAccess_project_release=CORAL-2-4-2
MySQLAccess_tag=$(tag)
MYSQLACCESSROOT=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/MySQLAccess
MySQLAccess_root=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/MySQLAccess
MYSQLACCESSVERSION=MySQLAccess-1-7-2
MySQLAccess_cmtpath=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
MySQLAccess_project=CORAL
MySQLAccess_project_release=CORAL-2-4-2
SQLiteAccess_tag=$(tag)
SQLITEACCESSROOT=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/SQLiteAccess
SQLiteAccess_root=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/SQLiteAccess
SQLITEACCESSVERSION=SQLiteAccess-1-7-0
SQLiteAccess_cmtpath=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
SQLiteAccess_project=CORAL
SQLiteAccess_project_release=CORAL-2-4-2
select_frontieraccess=FrontierAccess *
FrontierAccess_tag=$(tag)
FRONTIERACCESSROOT=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/FrontierAccess
FrontierAccess_root=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/FrontierAccess
FRONTIERACCESSVERSION=FrontierAccess-1-8-1
FrontierAccess_cmtpath=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
FrontierAccess_project=CORAL
FrontierAccess_project_release=CORAL-2-4-2
Tests_tag=$(tag)
TESTSROOT=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/Tests
Tests_root=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/Tests
TESTSVERSION=CoralTests-0-0-3
Tests_cmtpath=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
Tests_project=CORAL
Tests_project_release=CORAL-2-4-2
PYTHONPATH=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/../armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/CORAL/CORAL-2-4-2/../armv7l-fc21-gcc49-opt/python:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../QMtest/2.4.1_python2.7/armv7l-fc21-gcc49-opt/lib/python2.7/site-packages:/home/jwsmith/HDD/../armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/../armv7l-fc21-gcc49-opt/python:/home/jwsmith/HDD/lcgcmake-install-gcc49/ROOT/5.34.24/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/COOL/COOL_2_9_2/../armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/COOL/COOL_2_9_2/../armv7l-fc21-gcc49-opt/python:/home/jwsmith/HDD/COOL/COOL_2_9_2/python:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../CORAL/CORAL_2_4_4/armv7l-fc21-gcc49-opt/python:/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../CORAL/CORAL_2_4_4/armv7l-fc21-gcc49-opt/lib:/home/jwsmith/HDD/CORAL/CORAL-2-4-2/../armv7l-fc21-gcc49-opt/tests/bin:/home/jwsmith/HDD/../armv7l-fc21-gcc49-opt/tests/bin
uuid_tag=$(tag)
UUIDROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/uuid
uuid_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/uuid
UUIDVERSION=v1
uuid_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
uuid_offset=LCG_Interfaces
uuid_project=LCGCMT
uuid_project_release=LCGCMT_71
uuid_native_version=$(uuid_config_version)
uuid_home=$(LCG_external)/uuid/$(uuid_native_version)/$(LCG_system)
uuid_includes=$(uuid_home)/include
uuid_linkopts=-L$(uuid_home)/lib -luuid
uuid_export_paths= $(uuid_home)/include $(uuid_home)/lib
XercesC_tag=$(tag)
XERCESCROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/XercesC
XercesC_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/XercesC
XERCESCVERSION=v1
XercesC_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
XercesC_offset=LCG_Interfaces
XercesC_project=LCGCMT
XercesC_project_release=LCGCMT_71
XercesC_native_version=$(XercesC_config_version)
XercesC_home=$(LCG_external)/XercesC/$(XercesC_native_version)/$(LCG_system)
XercesC_linkopts=-L$(XercesC_home)/lib -lxerces-c -lpthread
XercesC_warnings=-w -Wno-unused
XercesC_cppflags= -DXERCESC_GE_31 
XercesC_export_paths= $(XercesC_home)/include $(XercesC_home)/lib
oracle_tag=$(tag)
ORACLEROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/oracle
oracle_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/oracle
ORACLEVERSION=v1
oracle_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
oracle_offset=LCG_Interfaces
oracle_project=LCGCMT
oracle_project_release=LCGCMT_71
oracle_native_version=$(oracle_config_version)
oracle_home=$(LCG_external)/oracle/$(oracle_native_version)/$(LCG_system)
oracle_export_paths= $(oracle_home)/include $(oracle_home)/lib $(oracle_home)/bin  $(TNS_ADMIN) 
oracle_linkopts=-L$(oracle_home)/lib -lclntsh
TNS_ADMIN=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../oracle/11.2.0.3.0/armv7l-fc21-gcc49-opt/admin
ORA_FPU_PRECISION=EXTENDED
NLS_LANG=american_america.WE8ISO8859P1
mysql_tag=$(tag)
MYSQLROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/mysql
mysql_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/mysql
MYSQLVERSION=v1
mysql_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
mysql_offset=LCG_Interfaces
mysql_project=LCGCMT
mysql_project_release=LCGCMT_71
mysql_native_version=$(mysql_config_version)
mysql_home=$(LCG_external)/mysql/$(mysql_native_version)/$(LCG_system)
mysql_linkopts=-L$(mysql_home)/lib -lmysqlclient_r 
mysql_export_paths= $(mysql_home)/include $(mysql_home)/lib 
sqlite_tag=$(tag)
SQLITEROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/sqlite
sqlite_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/sqlite
SQLITEVERSION=v1
sqlite_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
sqlite_offset=LCG_Interfaces
sqlite_project=LCGCMT
sqlite_project_release=LCGCMT_71
sqlite_native_version=$(sqlite_config_version)
sqlite_home=$(LCG_external)/sqlite/$(sqlite_native_version)/$(LCG_system)
sqlite_export_paths= $(sqlite_home)/include $(sqlite_home)/lib $(sqlite_home)/bin 
sqlite_linkopts=-L$(sqlite_home)/lib -lsqlite3
Frontier_Client_tag=$(tag)
FRONTIER_CLIENTROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/Frontier_Client
Frontier_Client_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/Frontier_Client
FRONTIER_CLIENTVERSION=v1
Frontier_Client_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
Frontier_Client_offset=LCG_Interfaces
Frontier_Client_project=LCGCMT
Frontier_Client_project_release=LCGCMT_71
Expat_tag=$(tag)
EXPATROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/Expat
Expat_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/Expat
EXPATVERSION=v1
Expat_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
Expat_offset=LCG_Interfaces
Expat_project=LCGCMT
Expat_project_release=LCGCMT_71
Expat_native_version=$(Expat_config_version)
Expat_home=$(LCG_external)/expat/$(Expat_native_version)/$(LCG_system)
Expat_linkopts=-L$(Expat_home)/lib -lexpat
Expat_name=expat
Expat_export_paths=$(Expat_home)/lib $(Expat_home)/include
Frontier_Client_native_version=$(Frontier_Client_config_version)
Frontier_Client_home=$(LCG_external)/frontier_client/$(Frontier_Client_native_version)/$(LCG_system)
Frontier_Client_linkopts=-L$(Frontier_Client_home)/lib -lfrontier_client
Frontier_Client_name=frontier_client
Frontier_Client_export_paths=$(Frontier_Client_home)/bin $(Frontier_Client_home)/lib $(Frontier_Client_home)/include
CppUnit_tag=$(tag)
CPPUNITROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/CppUnit
CppUnit_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/CppUnit
CPPUNITVERSION=v1
CppUnit_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
CppUnit_offset=LCG_Interfaces
CppUnit_project=LCGCMT
CppUnit_project_release=LCGCMT_71
CppUnit_native_version=$(CppUnit_config_version)
CppUnit_home=$(LCG_external)/CppUnit/$(CppUnit_native_version)/$(LCG_system)
CppUnit_linkopts=-L$(CppUnit_home)/lib -lcppunit -ldl
CppUnit_export_paths=$(CppUnit_home)/include $(CppUnit_home)/bin $(CppUnit_home)/lib
QMtest_tag=$(tag)
QMTESTROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/QMtest
QMtest_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/QMtest
QMTESTVERSION=v1
QMtest_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
QMtest_offset=LCG_Interfaces
QMtest_project=LCGCMT
QMtest_project_release=LCGCMT_71
QMtest_native_version=$(QMtest_config_version)_python$(Python_config_version_twodigit)
QMtest_home=$(LCG_external)/QMtest/$(QMtest_native_version)/$(LCG_system)
QM_home=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../QMtest/2.4.1_python2.7/armv7l-fc21-gcc49-opt
QMtest_export_paths=$(QMtest_home)
QMTEST_CLASS_PATH=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/config/qmtest
valgrind_tag=$(tag)
VALGRINDROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/valgrind
valgrind_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/valgrind
VALGRINDVERSION=v1
valgrind_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
valgrind_offset=LCG_Interfaces
valgrind_project=LCGCMT
valgrind_project_release=LCGCMT_71
valgrind_native_version=$(valgrind_config_version)
valgrind_home=$(LCG_external)/valgrind/$(valgrind_native_version)/$(LCG_system)
igprof_tag=$(tag)
IGPROFROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/igprof
igprof_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/igprof
IGPROFVERSION=v1
igprof_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
igprof_offset=LCG_Interfaces
igprof_project=LCGCMT
igprof_project_release=LCGCMT_71
libunwind_tag=$(tag)
LIBUNWINDROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/libunwind
libunwind_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/libunwind
LIBUNWINDVERSION=v1
libunwind_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
libunwind_offset=LCG_Interfaces
libunwind_project=LCGCMT
libunwind_project_release=LCGCMT_71
libunwind_native_version=$(libunwind_config_version)
libunwind_home=$(LCG_external)/libunwind/$(libunwind_native_version)/$(LCG_system)
libunwind_linkopts=-L$(libunwind_home)/lib -lunwind -lunwind-x86
libunwind_cppflags=-I $(libunwind_home)/include
libunwind_export_paths= $(libunwind_home)/include $(libunwind_home)/lib 
igprof_native_version=$(igprof_config_version)
igprof_home=$(LCG_external)/igprof/$(igprof_native_version)/$(LCG_system)
igprof_linkopts=-L$(igprof_home)/lib -ligprof
igprof_export_paths= $(igprof_home)/include $(igprof_home)/lib 
tcmalloc_tag=$(tag)
TCMALLOCROOT=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/tcmalloc
tcmalloc_root=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Interfaces/tcmalloc
TCMALLOCVERSION=v1
tcmalloc_cmtpath=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
tcmalloc_offset=LCG_Interfaces
tcmalloc_project=LCGCMT
tcmalloc_project_release=LCGCMT_71
tcmalloc_native_version=$(tcmalloc_config_version)
tcmalloc_home=$(LCG_external)/tcmalloc/$(tcmalloc_native_version)/$(LCG_system)
CORAL_CMTCONFIG_HASH=826
scrdir=$(CMTINSTALLAREA)/$(tag)/bin
CORAL_TESTSUITE_VALGRIND_SUPP=/home/jwsmith/HDD/../armv7l-fc21-gcc49-opt/bin/valgrind.supp
constituents=install_scripts install_includes install_pythonmods 
run_install_pythonmods=do_install_pythonmods
tag=armv7l-fc21-gcc49-opt
package=config
version=v1
PACKAGE_ROOT=$(CONFIGROOT)
srcdir=../src
bin=../$(config_tag)/
javabin=../classes/
mgrdir=cmt
BIN=/home/jwsmith/HDD/CORAL/CORAL-2-4-2/config/armv7l-fc21-gcc49-opt/
project=CORAL
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(CORAL_installarea_prefix)/$(CMTCONFIG)/lib $(CORAL_installarea_prefix)/share/lib $(CORAL_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(config_linkopts)  $(CoralCommon_linkopts)  $(RelationalAccess_linkopts)  $(CoralKernel_linkopts)  $(CoralBase_linkopts)  $(LCG_Policy_linkopts)  $(Boost_linkopts)  $(QMtest_linkopts)  $(Python_linkopts)  $(uuid_linkopts)  $(XercesC_linkopts)  $(oracle_linkopts)  $(mysql_linkopts)  $(sqlite_linkopts)  $(Frontier_Client_linkopts)  $(CppUnit_linkopts)  $(valgrind_linkopts)  $(igprof_linkopts)  $(tcmalloc_linkopts)  $(libunwind_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts)  $(LCG_Platforms_linkopts)  $(PyCoral_linkopts)  $(ConnectionService_linkopts)  $(RelationalService_linkopts)  $(MonitoringService_linkopts)  $(XMLAuthenticationService_linkopts)  $(EnvironmentAuthenticationService_linkopts)  $(XMLLookupService_linkopts)  $(OracleAccess_linkopts)  $(MySQLAccess_linkopts)  $(SQLiteAccess_linkopts)  $(FrontierAccess_linkopts)  $(Tests_linkopts) 
LCGCMT_installarea_prefix=$(cmt_installarea_prefix)
LCGCMT_installarea_prefix_remove=[.][.]
lcgcmake-install-gcc49_installarea_prefix=$(cmt_installarea_prefix)
lcgcmake-install-gcc49_installarea_prefix_remove=[.][.]
jwsmith_installarea_prefix=$(cmt_installarea_prefix)
jwsmith_installarea_prefix_remove=[.][.]
CORAL_installarea_prefix=$(cmt_installarea_prefix)
CORAL_installarea_prefix_remove=[.][.]
cmt_installarea_linkopts= -L/home/jwsmith/HDD/CORAL/CORAL-2-4-2/$(CORAL_installarea_prefix)/$(CMTCONFIG)/lib 
LCGCMT_home=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71
lcgcmake-install-gcc49_home=/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT
jwsmith_home=/home/jwsmith/HDD
CORAL_home=/home/jwsmith/HDD/CORAL/CORAL-2-4-2
CMTINSTALLAREA=/home/jwsmith/HDD/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements $(CoralCommon_root)/cmt/requirements $(RelationalAccess_root)/cmt/requirements $(CoralKernel_root)/cmt/requirements $(CoralBase_root)/cmt/requirements $(LCG_Policy_root)/cmt/requirements $(Boost_root)/cmt/requirements $(QMtest_root)/cmt/requirements $(Python_root)/cmt/requirements $(uuid_root)/cmt/requirements $(XercesC_root)/cmt/requirements $(oracle_root)/cmt/requirements $(mysql_root)/cmt/requirements $(sqlite_root)/cmt/requirements $(Frontier_Client_root)/cmt/requirements $(Expat_root)/cmt/requirements $(CppUnit_root)/cmt/requirements $(valgrind_root)/cmt/requirements $(igprof_root)/cmt/requirements $(tcmalloc_root)/cmt/requirements $(libunwind_root)/cmt/requirements $(LCG_Settings_root)/cmt/requirements $(LCG_Configuration_root)/cmt/requirements $(LCG_Platforms_root)/cmt/requirements $(PyCoral_root)/cmt/requirements $(ConnectionService_root)/cmt/requirements $(RelationalService_root)/cmt/requirements $(MonitoringService_root)/cmt/requirements $(XMLAuthenticationService_root)/cmt/requirements $(EnvironmentAuthenticationService_root)/cmt/requirements $(XMLLookupService_root)/cmt/requirements $(OracleAccess_root)/cmt/requirements $(MySQLAccess_root)/cmt/requirements $(SQLiteAccess_root)/cmt/requirements $(FrontierAccess_root)/cmt/requirements $(Tests_root)/cmt/requirements 
use_includes= $(ppcmd)"/home/jwsmith/HDD/CORAL/CORAL-2-4-2/CoralCommon" $(ppcmd)"/home/jwsmith/HDD/CORAL/CORAL-2-4-2/RelationalAccess" $(ppcmd)"/home/jwsmith/HDD/CORAL/CORAL-2-4-2/CoralKernel" $(ppcmd)"/home/jwsmith/HDD/CORAL/CORAL-2-4-2/CoralBase" $(ppcmd)"/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../Boost/1.55.0_python2.7/armv7l-fc21-gcc49-opt/include/boost-1_55" $(ppcmd)"/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../Python/2.7.6/armv7l-fc21-gcc49-opt/include/python2.7" $(ppcmd)"/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../uuid/1.42/armv7l-fc21-gcc49-opt/include" $(ppcmd)"/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../XercesC/3.1.1p1/armv7l-fc21-gcc49-opt/include" $(ppcmd)"/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../oracle/11.2.0.3.0/armv7l-fc21-gcc49-opt/include/" $(ppcmd)"/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../mysql/5.5.27/armv7l-fc21-gcc49-opt/include" $(ppcmd)"/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../mysql/5.5.27/armv7l-fc21-gcc49-opt/include/mysql" $(ppcmd)"/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../sqlite/3070900/armv7l-fc21-gcc49-opt/include" $(ppcmd)"/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../frontier_client/2.8.10/armv7l-fc21-gcc49-opt/include" $(ppcmd)"/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../CppUnit/1.12.1_p1/armv7l-fc21-gcc49-opt/include" $(ppcmd)"/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../igprof/5.9.11/armv7l-fc21-gcc49-opt/include" $(ppcmd)"/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../tcmalloc/1.7p3/armv7l-fc21-gcc49-opt/include" $(ppcmd)"/home/jwsmith/HDD/lcgcmake-install-gcc49/LCGCMT/LCGCMT_71/LCG_Settings/../../../libunwind/5c2cade/armv7l-fc21-gcc49-opt/include" $(ppcmd)"$(LCG_Platforms_root)/src" $(ppcmd)"$(PyCoral_root)/src" $(ppcmd)"$(ConnectionService_root)/src" $(ppcmd)"$(RelationalService_root)/src" $(ppcmd)"$(MonitoringService_root)/src" $(ppcmd)"$(XMLAuthenticationService_root)/src" $(ppcmd)"$(EnvironmentAuthenticationService_root)/src" $(ppcmd)"$(XMLLookupService_root)/src" $(ppcmd)"$(OracleAccess_root)/src" $(ppcmd)"$(MySQLAccess_root)/src" $(ppcmd)"$(SQLiteAccess_root)/src" $(ppcmd)"$(FrontierAccess_root)/src" $(ppcmd)"$(Tests_root)/src" 
use_fincludes= $(use_includes)
use_stamps=  $(config_stamps)  $(CoralCommon_stamps)  $(RelationalAccess_stamps)  $(CoralKernel_stamps)  $(CoralBase_stamps)  $(LCG_Policy_stamps)  $(Boost_stamps)  $(QMtest_stamps)  $(Python_stamps)  $(uuid_stamps)  $(XercesC_stamps)  $(oracle_stamps)  $(mysql_stamps)  $(sqlite_stamps)  $(Frontier_Client_stamps)  $(CppUnit_stamps)  $(valgrind_stamps)  $(igprof_stamps)  $(tcmalloc_stamps)  $(libunwind_stamps)  $(LCG_Settings_stamps)  $(LCG_Configuration_stamps)  $(LCG_Platforms_stamps)  $(PyCoral_stamps)  $(ConnectionService_stamps)  $(RelationalService_stamps)  $(MonitoringService_stamps)  $(XMLAuthenticationService_stamps)  $(EnvironmentAuthenticationService_stamps)  $(XMLLookupService_stamps)  $(OracleAccess_stamps)  $(MySQLAccess_stamps)  $(SQLiteAccess_stamps)  $(FrontierAccess_stamps)  $(Tests_stamps) 
use_cflags=  $(config_cflags)  $(CoralCommon_cflags)  $(RelationalAccess_cflags)  $(CoralKernel_cflags)  $(CoralBase_cflags)  $(LCG_Policy_cflags)  $(Boost_cflags)  $(QMtest_cflags)  $(Python_cflags)  $(uuid_cflags)  $(XercesC_cflags)  $(oracle_cflags)  $(mysql_cflags)  $(sqlite_cflags)  $(Frontier_Client_cflags)  $(CppUnit_cflags)  $(valgrind_cflags)  $(igprof_cflags)  $(tcmalloc_cflags)  $(libunwind_cflags)  $(LCG_Settings_cflags)  $(LCG_Configuration_cflags)  $(LCG_Platforms_cflags)  $(PyCoral_cflags)  $(ConnectionService_cflags)  $(RelationalService_cflags)  $(MonitoringService_cflags)  $(XMLAuthenticationService_cflags)  $(EnvironmentAuthenticationService_cflags)  $(XMLLookupService_cflags)  $(OracleAccess_cflags)  $(MySQLAccess_cflags)  $(SQLiteAccess_cflags)  $(FrontierAccess_cflags)  $(Tests_cflags) 
use_pp_cflags=  $(config_pp_cflags)  $(CoralCommon_pp_cflags)  $(RelationalAccess_pp_cflags)  $(CoralKernel_pp_cflags)  $(CoralBase_pp_cflags)  $(LCG_Policy_pp_cflags)  $(Boost_pp_cflags)  $(QMtest_pp_cflags)  $(Python_pp_cflags)  $(uuid_pp_cflags)  $(XercesC_pp_cflags)  $(oracle_pp_cflags)  $(mysql_pp_cflags)  $(sqlite_pp_cflags)  $(Frontier_Client_pp_cflags)  $(CppUnit_pp_cflags)  $(valgrind_pp_cflags)  $(igprof_pp_cflags)  $(tcmalloc_pp_cflags)  $(libunwind_pp_cflags)  $(LCG_Settings_pp_cflags)  $(LCG_Configuration_pp_cflags)  $(LCG_Platforms_pp_cflags)  $(PyCoral_pp_cflags)  $(ConnectionService_pp_cflags)  $(RelationalService_pp_cflags)  $(MonitoringService_pp_cflags)  $(XMLAuthenticationService_pp_cflags)  $(EnvironmentAuthenticationService_pp_cflags)  $(XMLLookupService_pp_cflags)  $(OracleAccess_pp_cflags)  $(MySQLAccess_pp_cflags)  $(SQLiteAccess_pp_cflags)  $(FrontierAccess_pp_cflags)  $(Tests_pp_cflags) 
use_pp_cppflags=  $(config_pp_cppflags)  $(CoralCommon_pp_cppflags)  $(RelationalAccess_pp_cppflags)  $(CoralKernel_pp_cppflags)  $(CoralBase_pp_cppflags)  $(LCG_Policy_pp_cppflags)  $(Boost_pp_cppflags)  $(QMtest_pp_cppflags)  $(Python_pp_cppflags)  $(uuid_pp_cppflags)  $(XercesC_pp_cppflags)  $(oracle_pp_cppflags)  $(mysql_pp_cppflags)  $(sqlite_pp_cppflags)  $(Frontier_Client_pp_cppflags)  $(CppUnit_pp_cppflags)  $(valgrind_pp_cppflags)  $(igprof_pp_cppflags)  $(tcmalloc_pp_cppflags)  $(libunwind_pp_cppflags)  $(LCG_Settings_pp_cppflags)  $(LCG_Configuration_pp_cppflags)  $(LCG_Platforms_pp_cppflags)  $(PyCoral_pp_cppflags)  $(ConnectionService_pp_cppflags)  $(RelationalService_pp_cppflags)  $(MonitoringService_pp_cppflags)  $(XMLAuthenticationService_pp_cppflags)  $(EnvironmentAuthenticationService_pp_cppflags)  $(XMLLookupService_pp_cppflags)  $(OracleAccess_pp_cppflags)  $(MySQLAccess_pp_cppflags)  $(SQLiteAccess_pp_cppflags)  $(FrontierAccess_pp_cppflags)  $(Tests_pp_cppflags) 
use_fflags=  $(config_fflags)  $(CoralCommon_fflags)  $(RelationalAccess_fflags)  $(CoralKernel_fflags)  $(CoralBase_fflags)  $(LCG_Policy_fflags)  $(Boost_fflags)  $(QMtest_fflags)  $(Python_fflags)  $(uuid_fflags)  $(XercesC_fflags)  $(oracle_fflags)  $(mysql_fflags)  $(sqlite_fflags)  $(Frontier_Client_fflags)  $(CppUnit_fflags)  $(valgrind_fflags)  $(igprof_fflags)  $(tcmalloc_fflags)  $(libunwind_fflags)  $(LCG_Settings_fflags)  $(LCG_Configuration_fflags)  $(LCG_Platforms_fflags)  $(PyCoral_fflags)  $(ConnectionService_fflags)  $(RelationalService_fflags)  $(MonitoringService_fflags)  $(XMLAuthenticationService_fflags)  $(EnvironmentAuthenticationService_fflags)  $(XMLLookupService_fflags)  $(OracleAccess_fflags)  $(MySQLAccess_fflags)  $(SQLiteAccess_fflags)  $(FrontierAccess_fflags)  $(Tests_fflags) 
use_pp_fflags=  $(config_pp_fflags)  $(CoralCommon_pp_fflags)  $(RelationalAccess_pp_fflags)  $(CoralKernel_pp_fflags)  $(CoralBase_pp_fflags)  $(LCG_Policy_pp_fflags)  $(Boost_pp_fflags)  $(QMtest_pp_fflags)  $(Python_pp_fflags)  $(uuid_pp_fflags)  $(XercesC_pp_fflags)  $(oracle_pp_fflags)  $(mysql_pp_fflags)  $(sqlite_pp_fflags)  $(Frontier_Client_pp_fflags)  $(CppUnit_pp_fflags)  $(valgrind_pp_fflags)  $(igprof_pp_fflags)  $(tcmalloc_pp_fflags)  $(libunwind_pp_fflags)  $(LCG_Settings_pp_fflags)  $(LCG_Configuration_pp_fflags)  $(LCG_Platforms_pp_fflags)  $(PyCoral_pp_fflags)  $(ConnectionService_pp_fflags)  $(RelationalService_pp_fflags)  $(MonitoringService_pp_fflags)  $(XMLAuthenticationService_pp_fflags)  $(EnvironmentAuthenticationService_pp_fflags)  $(XMLLookupService_pp_fflags)  $(OracleAccess_pp_fflags)  $(MySQLAccess_pp_fflags)  $(SQLiteAccess_pp_fflags)  $(FrontierAccess_pp_fflags)  $(Tests_pp_fflags) 
use_libraries= $(CoralCommon_libraries)  $(RelationalAccess_libraries)  $(CoralKernel_libraries)  $(CoralBase_libraries)  $(LCG_Policy_libraries)  $(Boost_libraries)  $(QMtest_libraries)  $(Python_libraries)  $(uuid_libraries)  $(XercesC_libraries)  $(oracle_libraries)  $(mysql_libraries)  $(sqlite_libraries)  $(Frontier_Client_libraries)  $(Expat_libraries)  $(CppUnit_libraries)  $(valgrind_libraries)  $(igprof_libraries)  $(tcmalloc_libraries)  $(libunwind_libraries)  $(LCG_Settings_libraries)  $(LCG_Configuration_libraries)  $(LCG_Platforms_libraries)  $(PyCoral_libraries)  $(ConnectionService_libraries)  $(RelationalService_libraries)  $(MonitoringService_libraries)  $(XMLAuthenticationService_libraries)  $(EnvironmentAuthenticationService_libraries)  $(XMLLookupService_libraries)  $(OracleAccess_libraries)  $(MySQLAccess_libraries)  $(SQLiteAccess_libraries)  $(FrontierAccess_libraries)  $(Tests_libraries) 
includes= $(ppcmd)"/home/jwsmith/HDD/CORAL/CORAL-2-4-2/config" $(use_includes)
fincludes= $(includes)
install_includes_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
install_pythonmods_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
install_scripts_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
tests_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
utilities_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
examples_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
all_constituents= $(constituents)
constituentsclean= install_pythonmodsclean install_includesclean 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituentsclean= examplesclean utilitiesclean testsclean install_scriptsclean makeclean 
