#ifndef GAUDIPARTPROP_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define GAUDIPARTPROP_MAJOR_VERSION 2
#define GAUDIPARTPROP_MINOR_VERSION 1
#define GAUDIPARTPROP_PATCH_VERSION 0
#define GAUDIPARTPROP_VERSION CALC_GAUDI_VERSION(GAUDIPARTPROP_MAJOR_VERSION,GAUDIPARTPROP_MINOR_VERSION)
#endif
