# Generated by GaudiProjectConfig.cmake (with CMake 2.8.12.2)

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)

# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

add_library(GaudiPluginService SHARED IMPORTED)
set_target_properties(GaudiPluginService PROPERTIES
  REQUIRED_LIBRARIES "dl"
  IMPORTED_SONAME "libGaudiPluginService.so"
  IMPORTED_LOCATION "${_IMPORT_PREFIX}/lib/libGaudiPluginService.so"
  )
add_executable(listcomponents IMPORTED)
set_target_properties(listcomponents PROPERTIES
  IMPORTED_LOCATION "${_IMPORT_PREFIX}/bin/listcomponents.exe"
  )
add_executable(Test_GaudiPluginService_UseCases IMPORTED)
set_target_properties(Test_GaudiPluginService_UseCases PROPERTIES
  IMPORTED_LOCATION "${_IMPORT_PREFIX}/bin/Test_GaudiPluginService_UseCases.exe"
  )

set(GaudiPluginService_VERSION v2r2)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
