#!/bin/sh
################################################################################################
#                               Joshua Wyatt Smith                                             #
#                               joshua.wyatt.smith@cern.ch                                     #
################################################################################################
export TCMALLOCDIR=$LCG_install/tcmalloc/1.7p3/$CMTCONFIG/lib
export PATH=$PATH:$TopDir/AtlasCore/AtlasCore-$VERSION/InstallArea/share/bin
export PYTHONPATH=$PYTHONPATH:$GaudiDir/InstallArea/$CMTCONFIG/jobOptions:$TopDir/AtlasCore/AtlasCore-$VERSION/InstallArea/jobOptions:$TopDir/AtlasCore/AtlasCore-$VERSION/InstallArea/python:$TopDir/AtlasCore/AtlasCore-$VERSION/Control/AthenaCommon/python:$GaudiDir/InstallArea/$CMTCONFIG/python
export JOBOPTSEARCHPATH=$JOBOPTSEARCHPATH:$GaudiDir/InstallArea/$CMTCONFIG/jobOptions:$TopDir/AtlasCore/AtlasCore-$VERSION/InstallArea/jobOptions
source $LCG_install/ROOT/5.34.24/$CMTCONFIG/bin/thisroot.sh
# Remember to set the LHAPDF_DATA_PATH when trying to run generators.
export LHAPDF_DATA_PATH=$TopDir/../Testing/AtlasOffline:$LHAPDF_DATA_PATH 
