#ifndef GAUDIUTILS_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define GAUDIUTILS_MAJOR_VERSION 5
#define GAUDIUTILS_MINOR_VERSION 3
#define GAUDIUTILS_PATCH_VERSION 0
#define GAUDIUTILS_VERSION CALC_GAUDI_VERSION(GAUDIUTILS_MAJOR_VERSION,GAUDIUTILS_MINOR_VERSION)
#endif
