#ifndef GAUDICOMMONSVC_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define GAUDICOMMONSVC_MAJOR_VERSION 3
#define GAUDICOMMONSVC_MINOR_VERSION 4
#define GAUDICOMMONSVC_PATCH_VERSION 0
#define GAUDICOMMONSVC_VERSION CALC_GAUDI_VERSION(GAUDICOMMONSVC_MAJOR_VERSION,GAUDICOMMONSVC_MINOR_VERSION)
#endif
